seed: 42
project_root: "/home/zhanghanlin/wangxu/test_run"
project_name: sasrec_hpsearch_1014
task_name: "sasrec_hpsearch_1014"
is_online: True
task_code: "hp_search"

# data
model_code: "sasrec"
train_data_sample_num : 1 
dataset : "Instruments"
data_path : "/home/zhanghanlin/wangxu/acdemic_2025/data/processed_data"
max_his_len : 20
add_prefix : False
test_sample_num: -1 # -1 表示全用
debug: False

# trainer
lr: 0.001
weight_decay: 0.00001
per_device_batch_size: 400
gradient_accumulation_steps: 1
warmup_ratio: 0.001
epochs: 200
lr_scheduler_type: constant
optim: adamw_torch
save_total_limit: 2
eval_save_strategy: epoch
logging_steps: 100
metric_for_best_model: eval_recall@10
greater_is_better: True
label_names: ["pos_item","neg_item"]
early_stopping_patience: 20
gradient_checkpointing: False
resume_from_checkpoint: False
no_cuda: False
# model
vocab_size: -1 # 自适应生成，而非配置
d_model: 64
seq_len: 20
dropout: 0.5
nhead: 2
dim_feedforward: 256
num_layers: 2

# hp_search
grid_search: False
hp_search_trial_num: 30
hp_search_direction: "maximize"
hp_search_metric: "test_recall@10"
hp_search_cate:
  lr: [0.01,0.005,0.001,0.0005,0.0001]
  weight_decay: [0.00001,0.0001,0.001,0.01]
  d_model: [64,128,32]
  n_heads: [1,2,3]
  n_layers: [1,2,3]
  dropout: [0.1,0.2,0.3,0.4,0.5]

hp_search_float: {}
hp_search_bind: {
  "dim_feedforward": "args.d_model * 4"
}

